# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Journey with CS
tagline:          'Jounrey into the world of computer science with Ankit Khare'
description:      'Sharing my computer sicence experience with the world.'
url:              https://ankit1khare.github.io/journeywithcs/
baseurl:          ''
permalink:        /:title/
author:
  name:           'Ankit Khare'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ankit1khare/
