# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Journey with CS
tagline:          'Journey into the world of computer science'
description:      'Sharing my computer science journey with the world'
url:              https://ankit1khare.github.io/journeywithcs/
baseurl:          'https://ankit1khare.github.io/journeywithcs/'
permalink:        /:title/
author:
  name:           'Ankit Khare'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ankit1khare/
